[mgr]
show_hidden = true

[opener]
edit = [
  { run = "vim %s", block = true, desc = "Open" },
]

open = [
  { run = "vim %s", desc = "Open" },
]

[[mgr.prepend_keymap]]
on   = "!"
for  = "windows"
run  = 'shell "bash" --block'
desc = "Open Git Bash here"
